// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// distSqrToVec
NumericVector distSqrToVec(NumericMatrix target, NumericVector query);
RcppExport SEXP _FastKNN_distSqrToVec(SEXP targetSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type target(targetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(distSqrToVec(target, query));
    return rcpp_result_gen;
END_RCPP
}
// buildKnnTree
List buildKnnTree(NumericMatrix target, int k);
RcppExport SEXP _FastKNN_buildKnnTree(SEXP targetSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type target(targetSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(buildKnnTree(target, k));
    return rcpp_result_gen;
END_RCPP
}
// queryKnnTree
List queryKnnTree(NumericVector query, int k, List pointers);
RcppExport SEXP _FastKNN_queryKnnTree(SEXP querySEXP, SEXP kSEXP, SEXP pointersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< List >::type pointers(pointersSEXP);
    rcpp_result_gen = Rcpp::wrap(queryKnnTree(query, k, pointers));
    return rcpp_result_gen;
END_RCPP
}
// destroyKnnTree
void destroyKnnTree(List pointers);
RcppExport SEXP _FastKNN_destroyKnnTree(SEXP pointersSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pointers(pointersSEXP);
    destroyKnnTree(pointers);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FastKNN_distSqrToVec", (DL_FUNC) &_FastKNN_distSqrToVec, 2},
    {"_FastKNN_buildKnnTree", (DL_FUNC) &_FastKNN_buildKnnTree, 2},
    {"_FastKNN_queryKnnTree", (DL_FUNC) &_FastKNN_queryKnnTree, 3},
    {"_FastKNN_destroyKnnTree", (DL_FUNC) &_FastKNN_destroyKnnTree, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_FastKNN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
