# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distSqrToVec <- function(target, query) {
    .Call(`_FastKNN_distSqrToVec`, target, query)
}

buildKnnTree <- function(target, k) {
    .Call(`_FastKNN_buildKnnTree`, target, k)
}

queryKnnTree <- function(query, k, pointers) {
    .Call(`_FastKNN_queryKnnTree`, query, k, pointers)
}

destroyKnnTree <- function(pointers) {
    invisible(.Call(`_FastKNN_destroyKnnTree`, pointers))
}

