# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

buildKnnTree <- function(target, k) {
    .Call(`_RANN_buildKnnTree`, target, k)
}

queryKnnTree <- function(query, k, pointers) {
    .Call(`_RANN_queryKnnTree`, query, k, pointers)
}

destroyKnnTree <- function(pointers) {
    invisible(.Call(`_RANN_destroyKnnTree`, pointers))
}

makeDouble <- function(x) {
    .Call(`_RANN_makeDouble`, x)
}

squareDouble <- function(x) {
    .Call(`_RANN_squareDouble`, x)
}

